### ISSUE TITLE
Setup failed for fht: Integration not found.

### ISSUE THREAD

**Issue by marcjohnen** [Rsclub22/home-assistant-fht#4]
I got stuck installing the plugin. I created a directory "custom_components" in the hass config directory:
![image](https://user-images.githubusercontent.com/3739890/202031427-1dd54df0-d291-46e9-8b1e-05e633669391.png)
Added my fht config file to the configuration.yaml
![image](https://user-images.githubusercontent.com/3739890/202031559-04cfddb8-78be-4b41-a9d3-b0f096633888.png)
Unzipped the module in the custom_components directory:
![image](https://user-images.githubusercontent.com/3739890/202031689-65078d42-3628-4702-ac8e-232275e4d541.png)
This is what the fht_heating folder looks like:
![image](https://user-images.githubusercontent.com/3739890/202031786-f1ea72ce-33f2-48b3-a4e0-6484aeb594c6.png)

When I restart home assistant I get this error:
![image](https://user-images.githubusercontent.com/3739890/202031918-589f547f-32d5-442d-8820-05cb5cd59c0e.png)

I'm running Home Assistant 2022.11.2 Frontend 20221108.0 - latest with docker-compose.

What am I doing wrong?

**Comment by Rsclub22** [comment]
Can you please try to integrate the whole section into the configuration.yaml without the extra file?

**Comment by multilan-tarek** [comment]
Hello Marc,

I also think the problem is with your inclusion of the configuration file.
See, in your log it says "fht" not found. The integration is called "fht_heating" and it got loaded.
It might work if you change "fht:" to "fht_heating:" but I'm not sure.

Home Assistant is generally picky about the configuration file.
The best and cleanest solution that I know works would be to put your climate related settings in a single file and include it like this:
`climate: !include climate.yaml`
The climate.yaml should of course not contain "climate:".
I think this is more or less a limitation of home assistant as the fht_heating integration is based on the generic climate integration. But don't take my word for this, there is probably a solution.

**Comment by Rsclub22** [comment]
As above said, i would instead use:
`climate: !include climate.yaml` in the configuration.yaml
 and then paste in the climate,yaml this instead:
```
  - platform: fht_heating
    address: "192.168.0.237:8086"
    dev_name: "FHT_BEDROOM"
```
This solution worked for me with docker. Please try to implement that.

**Comment by marcjohnen** [comment]
Thank you guys, I moved it to the configuration.yaml
![image](https://user-images.githubusercontent.com/3739890/202190766-27ad7dbb-d762-42f9-ab58-d4cabfff8550.png)
I'm not getting any errors, but also I can't see any FHT integration
![image](https://user-images.githubusercontent.com/3739890/202190970-d334f9cc-e369-4644-9c31-6da435952362.png)

**Comment by multilan-tarek** [comment]
We didn't implemented the gui setup, so it will never show up in the integrations tab. At least back then when we wrote the code, the home assistant dev documentation was really bad and it probably still is. The code examples just didn't worked and we never figured out why. 

But your climate entities should show up in the Entities page.

**Comment by marcjohnen** [comment]
Yes, they show up.
![image](https://user-images.githubusercontent.com/3739890/202234267-5fa55847-2856-42c5-9f69-bc19425b1cc1.png)
Appreciate your help.
